FROM ruby:2.4.0

RUN apt-get update && \
    apt-get install -y nodejs unzip postgresql-client-9.4 postgis \
      poppler-utils xlsx2csv python-dev python-pip && \
    rm -rf /var/lib/apt/lists/*

RUN pip install csvkit
RUN pip install clarify
RUN pip install --upgrade six

RUN gem install bundler

WORKDIR /app

ADD Gemfile /app/Gemfile
ADD Gemfile.lock /app/Gemfile.lock
RUN bundle install

ADD . /app

CMD ["rails", "server", "-P", "/tmp/railsomg.pid"]
